global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # ================================
  # PROMETHEUS ITSELF
  # ================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ================================
  # SPRING BOOT APPLICATION
  # ================================
  - job_name: 'gira-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8081']
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'

  # ================================
  # POSTGRESQL (via postgres_exporter)
  # ================================
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # ================================
  # RABBITMQ (via rabbitmq_exporter)
  # ================================
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 30s

  # ================================
  # CADVISOR (Container metrics)
  # ================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__name__]
        regex: '(container_.*)'
        action: keep

  # ================================
  # NODE EXPORTER (Host metrics)
  # ================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s





    